name: just_audio_web
description: Web platform implementation of just_audio. This implementation is endorsed and therefore doesn't require a direct dependency.
publish_to: none

flutter:
  plugin:
    platforms:
      web:
        pluginClass: JustAudioPlugin
        fileName: just_audio_web.dart

dependencies:
  just_audio_platform_interface: ^4.2.0
  # just_audio_platform_interface:
  #   path: ../just_audio_platform_interface
  # just_audio_platform_interface:
  #   git:
  #     url: https://github.com/AppifyLab/just_audio.git
  #     ref: visualizer
  #     path: just_audio_platform_interface
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
